### ISSUE TITLE
Case가 복수개면 bullet이나 괄호로 증명을 나누는게 좋습니다.

### ISSUE THREAD

**Issue by jeehoonkang** [drzix/Practice__Coq#1]
https://github.com/drzix/Practice__Coq/blob/94071098906db4ba99b53e4cef1f771afca922a2/Induction.v#L773

예컨대 위 라인은 저라면 다음과 같이 쓰겠습니다:

```coq
 replace (n + m) with (m + n).
 { reflexivity. }
```

**Comment by drzix** [comment]
넵, 우선 수정했습니다.
그런데 제가 의문을 갖게 된 것은 `assert`를 대신하여 `replace`를 사용하는 효용성입니다.

- `assert` 같은 경우 중간에 증명의 증명을 하게 됨으로써 잠시 부목적을 해결한 뒤 다시 주목적으로 돌아오는 흐름을 갖습니다만,
- `replace` 같은 경우 중간에 갑자기 부목적과 주목적이 바뀌게 되어 흐름이 지리멸렬하다는 느낌을 받습니다.

이런 점은 단순히 기호 사항인지, 아니면 특별히 `assert` 대신에 `replace`를 사용해야 마땅한 부분이 있는지 궁금합니다.

**Comment by jeehoonkang** [comment]
만일 부목적을 해결하는데 큰 노력이 들지 않는다면, replace를 하면 부목적을 hypothesis에 올리지 않아도 된다는 장점이 있습니다.

**Comment by drzix** [comment]
그런 장점이 있었군요. 감사합니다!
